# Generated by Django 5.2.7 on 2025-11-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='المدة الكلية (بالساعة)'),
        ),
    ]
