# Generated by Django 5.2.7 on 2026-03-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sleep_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.JSONField(default=list, verbose_name='المكونات'),
        ),
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_carbs',
            field=models.FloatField(default=0, verbose_name='إجمالي الكربوهيدرات'),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_fat',
            field=models.FloatField(default=0, verbose_name='إجمالي الدهون'),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_protein',
            field=models.FloatField(default=0, verbose_name='إجمالي البروتين'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_calories',
            field=models.IntegerField(default=0, verbose_name='إجمالي السعرات'),
        ),
    ]
