# Generated by Django 5.2.7 on 2026-03-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_meal_ingredients_meal_notes_meal_total_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نص الإجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الإجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='🔔', max_length=10, verbose_name='الأيقونة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشف؟'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='suggestions',
            field=models.JSONField(blank=True, default=list, verbose_name='اقتراحات'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('health', 'صحي'), ('nutrition', 'تغذوي'), ('sleep', 'نوم'), ('mood', 'مزاج'), ('habit', 'عادة'), ('alert', 'تنبيه'), ('reminder', 'تذكير'), ('achievement', 'إنجاز'), ('tip', 'نصيحة')], default='alert', max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-sent_at'], name='main_notifi_user_id_39dc89_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='main_notifi_user_id_844422_idx'),
        ),
    ]
