# Generated by Django 5.2.7 on 2026-03-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notification_action_text_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='معدل ضربات القلب (BPM)'),
        ),
    ]
