# Generated by Django 5.2.7 on 2026-04-04 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_healthstatus_heart_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رمز NDC')),
                ('brand_name', models.CharField(max_length=500, verbose_name='الاسم التجاري')),
                ('generic_name', models.CharField(blank=True, max_length=500, verbose_name='الاسم العلمي')),
                ('manufacturer', models.CharField(blank=True, max_length=500, verbose_name='الشركة المصنعة')),
                ('dosage_form', models.CharField(blank=True, max_length=200, verbose_name='شكل الجرعة')),
                ('route', models.CharField(blank=True, max_length=200, verbose_name='طريقة الاستخدام')),
                ('strength', models.CharField(blank=True, max_length=200, verbose_name='التركيز')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
            },
        ),
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='الجرعة')),
                ('frequency', models.CharField(blank=True, max_length=100, verbose_name='التكرار')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='وقت التذكير')),
                ('reminder_days', models.CharField(blank=True, max_length=50, verbose_name='أيام التذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medications', to='main.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دواء المستخدم',
                'verbose_name_plural': 'أدوية المستخدمين',
            },
        ),
    ]
