# Generated by Django 5.2.7 on 2026-04-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_medication_usermedication'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitdefinition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
    ]
