# Generated by Django 5.2.7 on 2026-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_habitdefinition_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthstatus',
            name='spo2',
            field=models.IntegerField(blank=True, null=True, verbose_name='نسبة الأكسجين في الدم (SpO2%)'),
        ),
    ]
