# Generated by Django 5.2.7 on 2026-04-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0008_healthstatus_spo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], max_length=20, null=True, verbose_name='مستوى النشاط'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='health_goal',
            field=models.CharField(blank=True, choices=[('loss', 'خسارة وزن'), ('gain', 'زيادة وزن'), ('maintain', 'تثبيت الوزن')], max_length=20, null=True, verbose_name='الهدف الصحي'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=10, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
